### ISSUE TITLE
Add gh-action to test on push to master

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30602]
When things have stabilized.

```
on:
  push:
    branches:
      - master
    tags-ignore: [ v.* ]
```
